name: mcMMO Party Admin
main: uk.co.drnaylor.mcmmopartyadmin.PartyAdmin
version: maven-version-number
depend: [mcMMO]
commands:
    partyadmin:
        aliases: [pa]
        description: Administrate parties
        permission: mcmmopartyadmin.commands.partyadmin
        permission-message: You don't have permission to perform that command
    fixparties:
        description: Fix parties
        permission: mcmmopartyadmin.commands.partyadmin
        permission-message: You don't have permission to perform that command
    partyspy:
        description: Toggle party spy
        permission-message: You don't have permission to perform that command
permissions:
    mcmmopartyadmin.commands.partyadmin:
        decription: Allows use of /partyadmin 
        default: op
    mcmmopartyadmin.spy:
        decription: Spy on party chat!
        default: op