name: mcMMO-PartyAdmin
main: uk.co.drnaylor.mcmmopartyadmin.PartyAdmin
version: maven-version-number
depend: [mcMMO]
api-version: 1.13
commands:
    partyadmin:
        aliases: [pa]
        description: Administrate parties
    fixparties:
        description: Fix parties
        permission: mcmmopartyadmin.admin
        permission-message: You don't have permission to perform that command
    partyspy:
        description: Toggle party spy
        permission-message: You don't have permission to perform that command
permissions:
    mcmmopartyadmin.admin:
        decription: Allows use of /partyadmin 
        default: op
    mcmmopartyadmin.spy:
        decription: Spy on party chat!
        default: op